/*parrfos que luego servirán para el despacho*/
let parrafo_1_proveyendo_al_escrito_inaugural = ("Proveyendo al escrito inaugural:");
let parrafo_2_proceso_digital = ('En primer lugar, se aclara que este proceso tramitará de forma enteramente digital (ac. 31/20 de la CSJN). Por ende, solo se admitirán escritos por intermedio del sistema Lex100 y toda documentación deberá ser incorporada de igual manera, quedando los originales bajo custodia de las personas interesadas hasta que el Juzgado los solicite. Cuando se actúa con patrocinio letrado, los escritos deberán contar con la firma ológrafa de la persona patrocinada (digitalizada por medios electrónicos) junto con la firma electrónica de la representación letrada. Las firmas olografas "copiadas y pegadas" en los escritos no tendrán valor. Sentados esos parámetros generales, se provee el escrito de inicio.');
let parrafo_3_por_presentado = ('Por presentado el consorcio ejecutante, por parte y por constituido el domicilio electrónico.');
let cual_es_el_capital_reclamado = prompt('¿Cuál es el capital reclamado?');
let monto_presupuestado_intereses_y_costas = (cual_es_el_capital_reclamado / 2);
let parrafo_4_intimacion_de_pago_tiene_dos_imputs = ('En atención a la documentación agregada y de conformidad con los arts. 2048 del Código Civil y Comercial y 524, 531 y 542 del Código Procesal, líbrese mandamiento de intimación de pago por la suma de $' + cual_es_el_capital_reclamado + ' con más la de $' + monto_presupuestado_intereses_y_costas + ' que provisionalmente se presupuesta para responder a intereses y costas. Hágase saber que la intimación de pago importará la citación de remate para oponer excepciones y el emplazamiento a consituir domicilio electrónico, bajo apercibimiento de mandar llevar adelante la ejecución y de hacer aplicable lo previsto en el art. 41 del Código Procesal. Al efecto, el proyecto de mandamiento deberá ser incorporado por intermedio del sistema Lex100 —sin necesidad de agregarlo con escrito—, el que luego será confrontado y enviado por Secretaría a la Oficina de Mandamientos. Esto último, siempre que se trate de diligencias a realizar en el ámbito de esta ciudad. De igual modo, déjese constancia en su texto que las copias de traslado de la demanda y su documentación se encuentran disponibles para su consulta pública en la página de Internet del Poder Judicial de la Nación (www.pjn.gov.ar).');
let parrafo_5_se_autoriza_bajo_responsabilidad = ('No obstante lo anterior, en salvaguarda de los principios de celeridad y economía procesal y con el fin de evitar demoras en el trámite del proceso, se hace saber que en el supuesto de fracasar la diligencia antes dispuesta, no será necesario solicitar su reiteración por escrito. En tal caso, puede acudirse a otras vías sin necesidad de petición alguna (art. 136 del Código Procesal), para lo cual se autoriza el libramiento de nuevos instrumentos ajustados a las constancias del acta de notificación, como la denuncia de nuevo domicilio, la habilitación de días y horas inhábiles e inclusive bajo responsabilidad de la parte ejecutante.');
let datos_del_inmueble_embargado = ('¿Cúales son los datos del inmueble objeto de embargo? (ingrese la dirección y si es alguna provincia o CABA)');

/*en embargo hay que chequear el tema de testimonio para embargo a provincia*/
let parrafo_6_embargo = ('Por las sumas indicadas anteriormente, trábese embargo sobre el bien ubicado en ' +  datos_del_inmueble_embargado + ', siempre que se encuentre en cabeza de la persona ejecutada. A cuyo fin, líbrese oficio de estilo o DEO, según el caso, al registro correspondiente.');
let parrafo_6A_embargo_pero_antes_tiene_que_cumplir_con_la_denuncia_del_nombre_del_ejecutado = ('Por las sumas indicadas anteriormente, trábese embargo sobre el bien ubicado en ' +  datos_del_inmueble_embargado + ' de esta ciudad, siempre que se encuentre en cabeza de la persona ejecutada, para lo cual deberá cumplirse de forma previa con la denuncia del nombre de la persona ejecutada. A cuyo fin, oportunamente líbrese oficio de estilo o DEO, según el caso, al registro que corresponda.');

let parrafo_7_tasa_pagada = ('Téngase por pagada la tasa de justicia.');
let parrafo_8_cumplio_con_bono = ('Agréguese el bono profesional.');
let parrafo_9_por_autorizados = ('Por autorizadas las personas indicadas, dejándose constancia que su intervención importará la notificación del estado del proceso (art. 134 del Código Procesal).');

/*chqquear si ahora no es Colegio Público de la Abogacia*/
let parrafo_10_no_cumplio_con_el_bono = ('Por no cumplirse con lo dispuesto en el art. 51, inc. “d”, de la ley 23.187, se intima para que en el plazo de 5 días se acompañe el bono profesional, bajo apercibimiento de comunicar tal circunstancia al Colegio Público de Abogados.');

let parrafo_11_no_pago_tasa = ('Intímase a la persona ejecutante para que en el plazo de cinco días proceda a pagar la tasa de justicia, bajo apercibimiento de lo dispuesto por los arts. 11 y 12 de la ley 23.898. Notifíquese por Secretaría.');
let parrafo_12_certificado_no_firmado_por_el_consejo = ('En atención a que el certificado de deuda por expensas no se encuentra aprobado por el Consejo de Propietarios/as (art. 2048 del Código Civil y Comercial), agregado que sea uno nuevo con la mencionada aprobación, se proveerá lo que en derecho corresponda.');
let parrafo_12a_certificado_no_firmado_por_el_consejo_ni_se_cumplio_con_330 = ('En atención a que el certificado de deuda por expensas no se encuentra aprobado por el Consejo de Propietarios/as (art. 2048 del Código Civil y Comercial) y a que no se denunció concrétamente el nombre de la persona ejecutada (art. 330, inc. "b", del Código Procesal), deberá cumplirse con tales recaudos de manera previa a la intimación de pago.');
let parrafo_13_intimacion_de_pago_sin_consejo_de_propietarios_tiene_dos_imputs = ('En atención a lo que resulta de la documentación agregada, la carencia de Consejo de Propietarios/as y de conformidad con los arts. 2048 del Código Civil y Comercial y 524, 531 y 542 del Código Procesal, líbrese mandamiento de intimación de pago por la suma de $' + cual_es_el_capital_reclamado + ' con más la de $' + monto_presupuestado_intereses_y_costas + ' que provisionalmente se presupuesta para responder a intereses y costas. Hágase saber que la intimación de pago importará la citación de remate para oponer excepciones y el emplazamiento a consituir domicilio electrónico, bajo apercibimiento de mandar llevar adelante la ejecución y de hacer aplicable a su respecto lo previsto en el art. 41 del Código Procesal.');
let parrafo_13a_intimacion_de_pago_sin_consejo_de_propietarios_con_previa_denuncia_de_demandado = ('Como previo a todo, deberá denunciarse concrétamente el nombre de la persona ejecutada, de conformidad con lo dispuesto por el art. 330, inc. "b", del Código Procesal. Una vez cumplido lo anterior, en atención a la documentación agregada, a la carencia de Consejo de Propietarios/as y de conformidad con los arts. 2048 del Código Civil y Comercial y 524, 531 y 542 del Código Procesal, líbrese mandamiento de intimación de pago por la suma de $' + cual_es_el_capital_reclamado + ' con más la de $' + monto_presupuestado_intereses_y_costas + ' que provisionalmente se presupuesta para responder a intereses y costas. Hágase saber que la intimación de pago importará la citación de remate para oponer excepciones y el emplazamiento a consituir domicilio electrónico, bajo apercibimiento de mandar llevar adelante la ejecución y de hacer aplicable a su respecto lo previsto en el art. 41 del Código Procesal. Al efecto, el proyecto de mandamiento deberá ser incorporado por intermedio del sistema Lex100 —sin necesidad de agregarlo con escrito—, el que luego será confrontado y enviado por Secretaría a la Oficina de Mandamientos. Esto último, siempre que se trate de diligencias a realizar en el ámbito de esta ciudad. De igual modo, déjese constancia en su texto que las copias de traslado de la demanda y su documentación se encuentran disponibles para su consulta pública en la página de Internet del Poder Judicial de la Nación (www.pjn.gov.ar).');
let parrafo_14_intimacion_de_pago_con_previa_agregacion_de_reglamento_tiene_dos_imputs = ('Como previo a todo, deberá incorporarse una copia digital del Reglamento de Propiedad Horizontal.Una vez cumplido lo anterior, de conformidad con los arts. 2048 del Código Civil y Comercial y 524, 531 y 542 del Código Procesal, líbrese mandamiento de intimación de pago por la suma de $' + cual_es_el_capital_reclamado + ' con más la de $' + monto_presupuestado_intereses_y_costas + ' que provisionalmente se presupuesta para responder a intereses y costas. Hágase saber que la intimación de pago importará la citación de remate para oponer excepciones y el emplazamiento a consituir domicilio electrónico, bajo apercibimiento de mandar llevar adelante la ejecución y de hacer aplicable a su respecto lo previsto en el art. 41 del Código Procesal. Al efecto, el proyecto de mandamiento deberá ser incorporado por intermedio del sistema Lex100 —sin necesidad de agregarlo junto con escrito—, el que luego será confrontado y enviado por Secretaría a la Oficina de Mandamientos. Esto último, siempre que se trate de diligencias a realizar en el ámbito de esta ciudad. De igual modo, déjese constancia en su texto que las copias de traslado de la demanda y su documentación se encuentran disponibles para su consulta pública en la página de Internet del Poder Judicial de la Nación (www.pjn.gov.ar).');
let parrafo_14a_intimacion_de_pago_con_previa_agregacion_de_reglamento_y_previa_denuncia_de_nombre_de_demandado_tiene_dos_imputs = ('Como previo a todo, deberá denunciarse concrétamente el nombre de la persona ejecutada (art. 330, inc. "b", del Código Procesal) e incorporarse una copia digital del Reglamento de Propiedad Horizontal. Una vez cumplido lo anterior, de conformidad con los arts. 2048 del Código Civil y Comercial y 524, 531 y 542 del Código Procesal, líbrese mandamiento de intimación de pago por la suma de $' + cual_es_el_capital_reclamado + ' con más la de $' + monto_presupuestado_intereses_y_costas + ' que provisionalmente se presupuesta para responder a intereses y costas. Hágase saber que la intimación de pago importará la citación de remate para oponer excepciones y el emplazamiento a consituir domicilio electrónico, bajo apercibimiento de mandar llevar adelante la ejecución y de hacer aplicable a su respecto lo previsto en el art. 41 del Código Procesal. Al efecto, el proyecto de mandamiento deberá ser incorporado por intermedio del sistema Lex100 —sin necesidad de agregarlo junto con escrito—, el que luego será confrontado y enviado por Secretaría a la Oficina de Mandamientos. Esto último, siempre que se trate de diligencias a realizar en el ámbito de esta ciudad. De igual modo, déjese constancia en su texto que las copias de traslado de la demanda y su documentación se encuentran disponibles para su consulta pública en la página de Internet del Poder Judicial de la Nación (www.pjn.gov.ar).');
let parrafo_15_no_trae_reglamento_y_el_certificado_esta_firmado_solo_por_el_admnistrador_sin_aclarar = ('En atención a que el certificado de deuda no se observa aprobado por el Consejo de Propietarios/as y a que no se acompañó copia del Reglamento de Propiedad Horizontal, aclare la persona peticionaria si se conformó el referido consejo y agregue copia del reglamento. En su caso, deberá incorporarse un nuevo certificado de conformidad con el art. 2048 del Código Civil y Comercial.');
let parrafo_15a_no_trae_reglamento_el_certificado_esta_firmado_solo_por_el_admnistrador_sin_aclarar_y_no_denuncia_nombre_de_demandado_se_vincula_con_el_anterior = ('Además de lo dispuesto en el punto anterior, también se deberá denunciar el nombre de la persona ejecutada, de conformidad con lo dispuesto por el art. 330, inc. "b", del Código Procesal.');
let parrafo_16_intimacion_de_pago_con_previa_agregacion_de_reglamento_cuando_denuncia_que_no_hay_consejo_de_propietarios_tiene_dos_imputs = ('Como previo a todo, deberá incorporarse una copia digital del Reglamento de Propiedad Horizontal. Una vez cumplido lo anterior y verificada con ello la carencia de Consejo de Propietarios/as, de conformidad con los arts. 2048 del Código Civil y Comercial y 524, 531 y 542 del Código Procesal, líbrese mandamiento de intimación de pago por la suma de $' + cual_es_el_capital_reclamado + ' con más la de $' + monto_presupuestado_intereses_y_costas + ' que provisionalmente se presupuesta para responder a intereses y costas. Hágase saber que la intimación de pago importará la citación de remate para oponer excepciones y el emplazamiento a consituir domicilio electrónico, bajo apercibimiento de mandar llevar adelante la ejecución y de hacer aplicable a su respecto lo previsto en el art. 41 del Código Procesal. Al efecto, el proyecto de mandamiento deberá ser incorporado por intermedio del sistema Lex100 —sin necesidad de agregarlo junto con escrito—, el que luego será confrontado y enviado por Secretaría a la Oficina de Mandamientos. Esto último, siempre que se trate de diligencias a realizar en el ámbito de esta ciudad. De igual modo, déjese constancia en su texto que las copias de traslado de la demanda y su documentación se encuentran disponibles para su consulta pública en la página de Internet del Poder Judicial de la Nación (www.pjn.gov.ar).');
let parrafo_16a_intimacion_de_pago_con_previa_agregacion_de_reglamento_cuando_denuncia_que_no_hay_consejo_de_propietarios_ademas_de_indicar_nombre_del_ejecutado_tiene_dos_imputs = ('Como previo a todo, deberá incorporarse una copia digital del Reglamento de Propiedad Horizontal y denunciarse el nombre de la persona ejecutada, de conformidad con lo dispuesto por el art. 330, inc. "b", del Código Procesal. Una vez cumplido lo anterior, de conformidad con los arts. 2048 del Código Civil y Comercial y 524, 531 y 542 del Código Procesal, líbrese mandamiento de intimación de pago por la suma de $' + monto_presupuestado_intereses_y_costas + ' con más la de $' + monto_presupuestado_intereses_y_costas + ' que provisionalmente se presupuesta para responder a intereses y costas. Hágase saber que la intimación de pago importará la citación de remate para oponer excepciones y el emplazamiento a consituir domicilio electrónico, bajo apercibimiento de mandar llevar adelante la ejecución y de hacer aplicable a su respecto lo previsto en el art. 41 del Código Procesal. Al efecto, el proyecto de mandamiento deberá ser incorporado por intermedio del sistema Lex100 —sin necesidad de agregarlo junto con escrito—, el que luego será confrontado y enviado por Secretaría a la Oficina de Mandamientos. Esto último, siempre que se trate de diligencias a realizar en el ámbito de esta ciudad. De igual modo, déjese constancia en su texto que las copias de traslado de la demanda y su documentación se encuentran disponibles para su consulta pública en la página de Internet del Poder Judicial de la Nación (www.pjn.gov.ar).');
let parrafo_17_intimacion_de_pago_con_previa_denuncia_de_nombre_de_ejecutado = ('Como previo a todo, deberá denunciarse concrétamente el nombre de la persona ejecutada, de conformidad con lo dispuesto por el art. 330, inc. "b", del Código Procesal. Una vez cumplido lo anterior, de conformidad con los arts. 2048 del Código Civil y Comercial y 524, 531 y 542 del Código Procesal, líbrese mandamiento de intimación de pago por la suma de $' + cual_es_el_capital_reclamado + ' con más la de $' + monto_presupuestado_intereses_y_costas + ' que provisionalmente se presupuesta para responder a intereses y costas. Hágase saber que la intimación de pago importará la citación de remate para oponer excepciones y el emplazamiento a consituir domicilio electrónico, bajo apercibimiento de mandar llevar adelante la ejecución y de hacer aplicable a su respecto lo previsto en el art. 41 del Código Procesal. Al efecto, el proyecto de mandamiento deberá ser incorporado por intermedio del sistema Lex100 —sin necesidad de agregarlo junto con escrito—, el que luego será confrontado y enviado por Secretaría a la Oficina de Mandamientos. Esto último, siempre que se trate de diligencias a realizar en el ámbito de esta ciudad. De igual modo, déjese constancia en su texto que las copias de traslado de la demanda y su documentación se encuentran disponibles para su consulta pública en la página de Internet del Poder Judicial de la Nación (www.pjn.gov.ar).');
let parrafo_18_mandato_vencido_de_administrador = ('No obstante lo que se indica en los puntos que siguen, atento a que el mandato de quien invoca la administración se encuentra vencido, acreditada que sea su vigencia se proveerá.');
let parrafo_19_acreditar_caracter_de_administrador = ('No obstante lo que se indica en los puntos que siguen, acreditada que sea la representación invocada por el/la administrador/a, se proveerá lo que corresponda.');
let parrafo_20_no_trae_el_reglamento = ('Por no haberse agregado, hágase saber que deberá incorporarse una copia digital del Reglamento de Propiedad Horizontal.');
let parrafo_21_no_denuncia_nombre_de_ejecutado = ('Al advertir que se reclamó contra el "propietario", también como previo deberá denunciarse el nombre de las personas ejecutadas, de conformidad con el art. 330, inc. "b", del Código Procesal.');
let caratula_del_expediente_conexo = prompt('Ingrese la caratula del expediente conexo');
let numero_del_expediente_conexo = prompt('Ingrese el número del expediente conexo');
let parrafo_22_resolucion_de_conexidad_por_periodos_anteriores = ('AUTOS, VISTOS Y CONSIDERANDO: Al consultar la caratula del proceso, surge conexidad con la causa' + caratula_del_expediente_conexo + ' (Expte. ' + numero_del_expediente_conexo + ', la cual tramita en este Juzgado. De sus constancias se advierte que el consorcio reclama respecto de igual unidad funcional y contra la misma persona ejecutada. No obstante, los periodos son diversos y el proceso referido se encuentra concluido. Entonces y al plantearse en esos términos la cuestión, recuerdo que la conexidad apta para producir el desplazamiento de la competencia debe basarse en una identidad entre las distintas pretensiones, derivada de la causa, del objeto o de ambos elementos, o en la existencia de una íntima vinculación entre los asuntos. En el primer caso, se tiende a evitar el riesgo del dictado de sentencias contradictorias, en tanto que en el segundo se persigue facilitar la solución de un litigio en base al conocimiento que tenga quien juzga de aquellas circunstancias que se debaten en otro u otros expedientes y que se relacionan de manera íntima con aquél.Sin embargo, tras el estudio de las constancias de este proceso y de las que se desprenden del expediente antes mencionado, no se advierte una vinculación que, a la luz de las pautas señaladas, aconseje la radicación de la presente causa ante este Juzgado. Lo dicho, puesto que en cada uno de los procesos se abarcan periodos distintos, además de que el primero de los procesos se encuentra concluido. En ese sentido, se ha decidido que no existe conexidad suficiente que aconseje el desplazamiento de la competencia entre dos ejecuciones de expensas, si se refieren a distintos períodos y si la primera de ellas se encuentra concluida, debiendo continuar su trámite ante el juzgado sorteado (conf. CNCiv., Trib. de Sup., “Cons. de Prop. Maure 3824 c/Massei Mugarza, María Carolina y otros s/ejecución de expensas”, 1/9/16). Por lo tanto, considero que se no justifica la asignación automática del expediente ante este Juzgado, por lo que me inhibo de entender en las presentes actuaciones, lo que ASI RESUELVO. En consecuencia, devuélvase la causa al Centro de Informática Judicial en formato digital, a los fines de su sorteo y ulterior adjudicación al Juzgado que corresponda, sirviendo la presente de atenta nota de envío. Regístrese.');
let parrafo_23_conexidad_sucesion_periodos_antes_muerto = ('AUTOS, VISTOS Y CONSIDERANDO: Al consultar la caratula del proceso, surge conexidad con la sucesión ' + caratula_del_expediente_conexo + ' (Expte. ' + numero_del_expediente_conexo + '), la cual tramita en este Juzgado. De sus constancias y de lo que surge del presente juicio, se advierte que las expensas aquí reclamadas se devengaron con posterioridad a la muerte del causante. Al ser así, recuerdo que el art. 2336 del Código Civil y Comercial dispone que el Juzgado competente para entender en el proceso sucesorio debe conocer en las acciones de petición de herencia, nulidad de testamento, de los demás litigios que tienen lugar con motivo de la administración y liquidación de la herencia, de la ejecución de las disposiciones testamentarias, del mantenimiento de la indivisión, de las operaciones de partición, de la garantía de los lotes entre los copartícipes y de la reforma y nulidad de partición. No obstante, la Corte Suprema de Justicia dejó sentado que las acciones de carácter personal originadas con anterioridad al fallecimiento del o la causante resultaban atraídas por la sucesión en los términos del inc. 4° del art. 3284 del Código Civil. Ese criterio —según expresó el Máximo Tribunal— se mantiene frente a la entrada en vigencia del Código Civil y Comercial (CSJN, “V. de M., M. c/ PAMI s/ Ds. y ps.”, 8/9/2015, AR/JUR/30823/2015). En igual sentido lo decidió el Tribunal de Superintendencia, el que dispuso que el fuero de atracción regulado en el art. 2336 del Código Civil y Comercial no aporta novedades con relación al viejo art. 3284 del Código derogado (CNCiv., Tribunal de Superintendencia, “AFIP c/ Sucesión de M., R. s/ Ej. fiscal”, Expte. 66.291). Ahora bien, en función de los referidos márgenes del fuero de atracción, advierto que en la especie no cabe aplicar tal desplazamiento de la competencia y aceptar la radicación del proceso, puesto que —como ya se dijo— el Consorcio ejecutante reclama períodos posteriores a la muerte de la persona cuya sucesión tramita en este Juzgado. Es decir, la deuda no es de la sucesión sino de los herederos de la persona fallecida. Por ende, considero que se no justifica la asignación automática del expediente ante este Juzgado, razón me conduce a inhibirme de entender en las presentes actuaciones, lo que ASI RESUELVO. En consecuencia, devuélvase la causa al Centro de Informática Judicial a los fines de su sorteo y posterior adjudicación. Regístrese.');

/*comienzo de arbol*/
let surge_conexidad_de_caratula = prompt('¿Surge alguna conexidad de la caratula?');
    if (surge_conexidad_de_caratula == "NO") {
        let calidad_administrador = prompt ("¿El administrador acreditó su calidad?");
            if (calidad_administrador == "SI"){
                let se_indica_nombre_ejecutado_o_solo_propietario = prompt ('¿Se indica el nombre del ejecutado o se reclama solo contra el "propietario"?');
                    if (se_indica_nombre_ejecutado_o_solo_propietario == "SI"){
                        let trajeron_el_reglamento_propiedad = prompt ("¿Trajeron el Reglamento de Propiedad Horizontal?");
                            if (trajeron_el_reglamento_propiedad == "SI"){
                                let hay_consejo_de_propietarios = prompt ("¿Hay Consejo de Propietarios?");
                                    if (hay_consejo_de_propietarios == "SI");{
                                        let esta_firmado_el_certificado_por_administrador_y_consejo = prompt ('¿El certificado está firmado por el Consejo de Propietarios y el administrador?');
                                            if (esta_firmado_el_certificado_por_administrador_y_consejo == "SI, POR AMBOS");{
                                                cual_es_el_capital_reclamado;
                                                let pide_embargo_sobre_el_inmueble = prompt('¿Pide embargo sobre el inmueble?');
                                                    if (pide_embargo_sobre_el_inmueble == "SI"); {
                                                        datos_del_inmueble_embargado;
                                                        let pago_tasa_de_justicia = prompt('¿Pago tasa de justicia?');
                                                            if (pago_tasa_de_justicia == "SI") {
                                                                let trajo_el_bono_profesional = prompt ('¿Trajo el bono profesional?');
                                                                    if (trajo_el_bono_profesional == 'SI') {;
                                                                        let autorizo_a_alguien = prompt ('¿Autorizó a alguien?');
                                                                            if (autorizo_a_alguien == 'SI') {
                                                                                document.write (parrafo_1_proveyendo_al_escrito_inaugural, parrafo_2_proceso_digital, parrafo_3_por_presentado, parrafo_4_intimacion_de_pago_tiene_dos_imputs, parrafo_5_se_autoriza_bajo_responsabilidad, parrafo_6_embargo, parrafo_7_tasa_pagada, parrafo_8_cumplio_con_bono, parrafo_9_por_autorizados); 
                                                                            }
                                                            }
                                                    }
                                            } 
                                    }    
                            }
                    }
                    else if (se_indica_nombre_ejecutado_o_solo_propietario == "NO SE INDICA"){};
            }else if (calidad_administrador == "TIENE EL MANDATO VENCIDO") {
                alert ("sigue bien hasta acá");
            }else if (calidad_administrador == "NO") {
                alert ("de pedo también sigue bien hasta acá");
            }}
    else alert ("SI HAY CONEXIDAD");



